In [1]:
import numpy as np


In [3]:
minhalista = [1,2,3]


In [5]:
np.array(minhalista)

array([1, 2, 3])

In [7]:
minhamatriz = [[1,2,3], [4,5,6], [7,8,9]]

In [9]:
np.array(minhamatriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
arr = np.zeros(3)
arr

array([0., 0., 0.])

In [25]:
mat = np.zeros((5,5))

In [27]:
mat

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
np.linspace(0,10,2)

array([ 0., 10.])

In [35]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [49]:
np.linspace(0,15,4)

array([ 0.,  5., 10., 15.])

In [51]:
np.random.rand(5)

array([0.80658514, 0.54245829, 0.14868336, 0.33751317, 0.46653766])

In [53]:
np.random.rand(5) * 100

array([94.58873896, 93.90579148, 22.32287524, 51.47357832, 82.72911483])

In [55]:
np.random.rand(5,4)

array([[0.69401258, 0.67531715, 0.87426076, 0.87144482],
       [0.23296023, 0.48790595, 0.38491182, 0.38597197],
       [0.14724634, 0.38050439, 0.49611874, 0.684046  ],
       [0.38364099, 0.03212874, 0.30352429, 0.44472165],
       [0.31458874, 0.09225377, 0.72843082, 0.90338424]])

In [57]:
np.random.randn(4)

array([ 0.74303431, -1.62845492, -0.96323183, -0.57887424])

In [59]:
np.random.randint(0,100,10)

array([37, 44, 64, 66,  6, 75, 99, 83,  2,  1])

In [65]:
np.around(np.random.rand(5) * 100, 0) 

array([68., 24., 58., 94., 66.])

In [67]:
arr = np.random.rand(25)

In [69]:
arr


array([0.11868112, 0.0532342 , 0.66256125, 0.68516834, 0.58217344,
       0.53141158, 0.65042231, 0.01827175, 0.3654666 , 0.19423083,
       0.53482347, 0.01974815, 0.37784273, 0.52862588, 0.10076138,
       0.79618243, 0.72938106, 0.65223364, 0.65560883, 0.72515067,
       0.77081735, 0.04629129, 0.21692198, 0.72093358, 0.99725091])

In [71]:
arr.reshape((5,5))

array([[0.11868112, 0.0532342 , 0.66256125, 0.68516834, 0.58217344],
       [0.53141158, 0.65042231, 0.01827175, 0.3654666 , 0.19423083],
       [0.53482347, 0.01974815, 0.37784273, 0.52862588, 0.10076138],
       [0.79618243, 0.72938106, 0.65223364, 0.65560883, 0.72515067],
       [0.77081735, 0.04629129, 0.21692198, 0.72093358, 0.99725091]])

In [73]:
arr1 = arr.reshape((5,5))

In [79]:
arr1

array([[0.11868112, 0.0532342 , 0.66256125, 0.68516834, 0.58217344],
       [0.53141158, 0.65042231, 0.01827175, 0.3654666 , 0.19423083],
       [0.53482347, 0.01974815, 0.37784273, 0.52862588, 0.10076138],
       [0.79618243, 0.72938106, 0.65223364, 0.65560883, 0.72515067],
       [0.77081735, 0.04629129, 0.21692198, 0.72093358, 0.99725091]])

In [81]:
arr1.shape

(5, 5)

In [83]:
arr.shape

(25,)

In [87]:
arr.max()

0.9972509100835263

In [89]:
arr.min()

0.01827174563807976

In [91]:
arr.argmax()

24

In [93]:
arr1.argmax()

24