In [1]:
import numpy as np

In [21]:
#sequencia de fibonacci
fibonacci = np.zeros(10, dtype=int)
fibonacci[0], fibonacci[1] = 0, 1

for i in range(2, 10):
    fibonacci[i] = fibonacci[i-1] + fibonacci[i-2]

fibonacci

array([ 0,  1,  1,  2,  3,  5,  8, 13, 21, 34])

In [31]:
#quantidade de vezes que um lado do dado caiu
lancamentos = np.random.randint(1, 7, 1000)

for i in range(1, 7):
    print(f"{i}: {np.sum(lancamentos == i)} vezes")

1: 171 vezes
2: 162 vezes
3: 168 vezes
4: 169 vezes
5: 164 vezes
6: 166 vezes


In [41]:
notas = np.random.uniform(0, 10, 10)

print("Nota média:", np.mean(notas))
print("Nota mínima:", np.min(notas))
print("Nota máxima:", np.max(notas))
print("Número de alunos aprovados", np.sum(notas >= 5))

Nota média: 5.218084845768135
Nota mínima: 0.9971879140927242
Nota máxima: 8.239834274943846
Número de alunos aprovados 6


In [57]:
#indexacao de arrays
arr = np.arange(10)  
print('Vetor completo: ', arr)
print('Ultimos 3 elementos do vetor : ', arr[-3:])
print('Do segundo elemento do vetor até o final: ', arr[1:])
print('Formatação vetor: ', arr.reshape(2,5))

Vetor completo:  [0 1 2 3 4 5 6 7 8 9]
Ultimos 3 elementos do vetor :  [7 8 9]
Do segundo elemento do vetor até o final:  [1 2 3 4 5 6 7 8 9]
Formatação vetor:  [[0 1 2 3 4]
 [5 6 7 8 9]]


In [67]:
zeros = np.zeros((2, 2))  
ones = np.ones((2, 5))    
rando = np.random.rand(5)  

print("Matriz de zeros:\n", zeros)
print("Matriz de uns:\n", ones)
print("Array de valores aleatórios:", rando)

Matriz de zeros:
 [[0. 0.]
 [0. 0.]]
Matriz de uns:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Array de valores aleatórios: [0.87252015 0.69165566 0.14859175 0.22021952 0.67707714]
